# @file neoforge.mods.toml
# @spec TOML v0.5.0 (https://github.com/toml-lang/toml)
modLoader="javafml"
loaderVersion="${version_range_loader}"
issueTrackerURL="${meta_issues}"
license="${meta_license}"

[[mixins]]
config="${meta_modid}.mixins.json"

[[mods]]
modId="${meta_modid}"
version="${version_mod}"
displayName="${meta_modname}"
description='''${meta_description}'''
authors="${meta_author}"
credits="The Smiths and Weavers of the World."
updateJSONURL="${meta_updateurl}"
displayURL="${meta_download}"
logoFile="assets/${meta_modid}/logo.png"

[[dependencies.${meta_modid}]]
  modId="neoforge"
  type="required"
  versionRange="${version_range_neoforge}"
  ordering="NONE"
  side="BOTH"

[[dependencies.${meta_modid}]]
  modId="minecraft"
  type="required"
  versionRange="[${version_minecraft}]"
  ordering="NONE"
  side="BOTH"



# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"
