# @file neoforge.mods.toml
# @spec TOML v0.5.0 (https://github.com/toml-lang/toml)
modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="${meta_issues}"
license="${mod_license}"

[[mixins]]
config="${mod_id}.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''
authors="${mod_authors}"
credits="The Smiths and Weavers of the World."
updateJSONURL="${meta_updateurl}"
displayURL="${meta_download}"
logoFile="assets/${mod_id}/logo.png"

[[dependencies.${mod_id}]]
  modId="neoforge"
  type="required"
  versionRange="${neo_version_range}"
  ordering="NONE"
  side="BOTH"

[[dependencies.${mod_id}]]
  modId="minecraft"
  type="required"
  versionRange="[${minecraft_version}]"
  ordering="NONE"
  side="BOTH"



# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"
